### ISSUE TITLE
L.Control.Draw is not a function - after upgrade from 0.8.7 to 0.10.0

### ISSUE THREAD

**Issue by mobidev111** [tombatossals/angular-leaflet-directive#1042]
Angular leaflet seems to cause an issue with Leaflet Draw:

```
TypeError: L.Control.Draw is not a function
```

nothing changed in a working set of code - only upgraded from 0.8.7 to 0.10.0

**Comment by AnnieGitUrGun** [comment]
I am experiencing this problem as well. Has anyone been able to figure out what's going on?

**Comment by elbow-jason** [comment]
ditto

**Comment by msquee** [comment]
Experiencing this as well.

**Comment by massilva** [comment]
I too.
